services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /data/compose/9/audiobookshelf_data:/audiobooks
      - /data/compose/9/audiobookshelf_data:/podcasts
      - /data/compose/9/audiobookshelf_data:/metadata
      - /data/compose/9/audiobookshelf_data:/config
    restart: unless-stopped
networks:
  nginxpm:
    external: true