version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: Gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # QBitTorrent's User Interface
      - 6880:6880 # QBitTorrent's TCP Port
      - 6880:6880/udp # QBitTorrent's UDP Port
    volumes:
      - /volume1/docker/gluetun/config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=expressvpn

      - SERVER_COUNTRIES=America
      - TZ=America/Los_Angeles
      - UPDATER_PERIOD=24h
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: QBitTorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/Los_Angeles
      - WEBUI_PORT=8080
    volumes:
      - /volume1/docker/qbt/config:/config
      - /volume1/data/downloads/qbt/torrents:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
    restart: always