services:
  mariadb:
    container_name: Nextcloud-DB
    image: mariadb:11.4-noble #LTS Long Time Support Until May 29, 2029.
    security_opt:
      - no-new-privileges:false
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - /volume1/docker/nextcloud/db:/var/lib/mysql:rw
      - /volume1/docker/nextcloud/db:/etc/mysql/conf.d:rw
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_PASSWORD=Password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TZ=America/Los_Angeles
    restart: on-failure:5
      
  redis:
    image: redis
    container_name: Nextcloud-REDIS
    hostname: nextcloudredis
    user: 1026:100
    healthcheck:
     test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - /volume1/docker/nextcloud/redis:/data:rw
    environment:
      TZ: America/Los_Angeles
    restart: on-failure:5
      
  nextcloud:
    container_name: Nextcloud
    ports:
      - 8082:80
    depends_on:
      mariadb:
       condition: service_started
      redis:
       condition: service_healthy
    environment:
      - REDIS_HOST=nextcloudredis
      - NEXTCLOUD_ADMIN_USER=User_name
      - NEXTCLOUD_ADMIN_PASSWORD=Password
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.synology.me 192.168.1.24
      - TRUSTED_PROXIES=192.168.1.24
      - OVERWRITEHOST=nextcloud.synology.me
      - OVERWRITEPROTOCOL=https
      - MYSQL_PASSWORD=Password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    volumes:
      - /volume1/docker/nextcloud/html:/var/www/html:rw
      - /volume1/docker/nextcloud/custom_apps:/var/www/html/custom_apps:rw
      - /volume1/docker/nextcloud/config:/var/www/html/config:rw
      - /volume1/docker/nextcloud/data:/var/www/html/data:rw
      - /volume1/docker/nextcloud/themes:/var/www/html/themes:rw
    image: nextcloud
    restart: on-failure:5
    
  cron:
   image: nextcloud:apache
   container_name: Nextcloud-CRON
   restart: always
   volumes:
     - /volume1/docker/nextcloud/config:/var/www/html/config:rw
     - /volume1/docker/nextcloud/html:/var/www/html:rw
     - /volume1/docker/nextcloud/custom_apps:/var/www/html/custom_apps:rw
     - /volume1/docker/nextcloud/data:/var/www/html/data:rw
   entrypoint: /cron.sh
   depends_on:
    mariadb:
       condition: service_started
    redis:
       condition: service_started