version: '3'
services:
    db:
        image: postgres:16
        volumes:
            - /volume1/docker/joplin:/var/lib/postgresql/data
        ports:
            - 5432:5432
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=testing123
            - POSTGRES_USER=joplin
            - POSTGRES_DB=joplindb
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - 22300:22300
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=http://192.168.1.24:22300
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=testing123
            - POSTGRES_DATABASE=joplindb
            - POSTGRES_USER=joplin
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db