version: "3.9"
services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: PlexHW
    hostname: plex
    network_mode: host
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:32400/web
    volumes:
      - /volume1/docker/plexhw:/config:rw
      - /volume1/movies/media:/movies:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      TZ: Europe/Bucharest
      PUID: 1026
      PGID: 100
      VERSION: public
      PLEX_CLAIM: YourPLEXClaimCode # STEP 4
    restart: on-failure:5