version: "3"
services:
  app:
    container_name: mealie
    image: hkotel/mealie:v2.7.1
    restart: unless-stopped
    volumes:
      - mealie_data:/app/data
    ports:
      - "9925:9000"
volumes:
  mealie_data: